name: app
description: Trading Intelligence Network

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  oauth2_client: 2.3.0
  github: any
  freezed_annotation: ^1.0.0
  flutter_riverpod: ^1.0.0
  equatable: ^2.0.3
  logger: ^1.0.0
  auto_route: 3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.1
  freezed: ^1.0.0
  build_runner: ^2.1.5
  auto_route_generator: 3.1.0

flutter_native_splash:
  color: "#020001"
  image: assets/sa_logo.png
  android: true
  ios: true

flutter:

  uses-material-design: true

